### ISSUE TITLE
Share fire

### ISSUE THREAD

**Issue by guivazcabral** [FogosPT/fogosmobile#4]
On the web app it is possible to share a fire on social media via the fire details panel.
We must have the same feature on the mobile apps, and I think the buttons should be on the fire bottom sheet and not on the "more info" screen

**Comment by Vanethos** [comment]
For reference, here is the Share text for twitter:

```
[02-05-2019 07:56] Incêndio em Viana Do Castelo, Viana Do Castelo, Perre https://fogos.pt/fogo/2019160013085
```

So, the template should be

```
[$TIME$] Incêndio em $LOCATION$ $LINK$
```

For both WhatsApp and Facebook, we just share the $LINK$ since it will create embebed content

```
https://fogos.pt/fogo/2019160013085
```

@guivazcabral  can you confirm this?

**Comment by guivazcabral** [comment]
@Vanethos sounds good

**Comment by Vanethos** [comment]
@guivazcabral after further inspection, the majority of the plugins for Flutter use a single message for sharing data, see:

https://pub.dartlang.org/packages/share

This is due to the fact that in apps, we usually have 1 button to handle the share, and not all 3 that are present in the website at the moment (since the user might not have twitter or facebook installed in their phone but they might want to send an sms, for example)

As such, what should be the correct message to display and send?

**Comment by guivazcabral** [comment]
you can go ahead and use the template you mentioned in your first comment.

on the bottom sheet, maybe lose the dividers on the info blocks and change the icon colors to the color of the fire marker on the map.

with the name of the town on the header, and the buttons' placement (the share button, the close button and soon the notification subscription button), we'll have a problem with long city names. maybe change those buttons to the footer of the bottom sheet, aligned to the right, and in the future, on the left part of the footer, we'll add the '+ info' button that will lead to the fire details screen.

**Comment by Vanethos** [comment]
if you agree, since we are adding the subscribe functionality in #1, I will make a PR with the current design.

We will then create a new issue to change the placement of the buttons, which can be a good first-issue for newcomers. 

The other changes (Divider and color) are corrected in this new commit
