### ISSUE TITLE
Add satellite view to map

### ISSUE THREAD

**Issue by tomahock** [FogosPT/fogosmobile#61]

**Comment by Vanethos** [comment]
Since we are retrieving the map tiles and displaying them on [flutter_maps](https://github.com/johnpryan/flutter_map) plugin, the following changes must be done.

In 

```dart
TileLayerOptions(
                          urlTemplate:
                              "https://api.mapbox.com/styles/v1/fogospt/{id}/tiles/256/{z}/{x}/{y}?access_token={accessToken}",
                          additionalOptions: {
                            'accessToken':
                                'pk.eyJ1IjoiZm9nb3NwdCIsImEiOiJjamZ3Y2E5OTMyMjFnMnFxbjAxbmt3bmdtIn0.xg1X-A17WRBaDghhzsmjIA',
                            'id': 'cjgppvcdp00aa2spjclz9sjst',
                          },
                        )
```

verify if there is a way to change the `id` to match the id of sattelite:

https://docs.mapbox.com/api/maps/#example-request-retrieve-a-static-map-from-a-style

**Comment by guivazcabral** [comment]
already laid down the ground work to make this function like it's supposed to. check the fire list page and the variables file
